NvChad/NvChad

lua/nvimTree/lua.lua

Why not make an alias of cmd first and then use cmd instead of vim.cmd

aliases on the top

---

install.sh

Normal said gives `command a expects \ followed by text` error `gsed` which is part of gnu coreutils for macOS works

use gnu sed in mac

---

install.sh

With the changing of file names and file structure the ability to select your own shell didn't work.

Fix a smaller error that prevents the changing of shells

---

lua/mappings.lua
lua/nvim-lspconfig.lua
lua/pluginList.lua

By using [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) I added an `lspinstall` function to easily allow users to install their own langauge servers. This could probably remove the hardcoded lsps in `nvim-lspcofig.lua` but i didn't want to remove anything yet.

Add `lspinstall` functionality

---

lua/highlights.lua

In the highlights.lua 
vim.cmd is changed to cmd as it is imported like that

cmd instead of vim.cmd

---

lua/pluginList.lua

TrueZen.nvim repository address has been changed from https://github.com/kdav5758/TrueZen.nvim to https://github.com/Pocco81/TrueZen.nvim. Without changing plugin path in pluginList.lua file, plugin cannot be updated.

Update TrueZen.nvim after repository changed address

---

lua/mappings.lua
lua/utils.lua

This is a pretty small commit/pull, hope that's okay
This fixes an escape mapping and terminal opening mapping
**Fixes:**
1. escape 'jk' mapping not working in terminal mode
2. escape 'jk' mapping not working in visual mode
3. opening a new terminal buffer (with `<CNTL> + t + t`) did not hide line numbers
(only after viewing another buffer and returning)
it did work for the `<CNTL> + l` & `<CNTL> + x` mappings, as they were just splits
(it still works for these mappings)
Planning to investigate some more term config, but starting with this
tl;dr: can escape term & visual better, 
monkeh still cannot escape the sad

Fix terminal config issues

---

install.sh
lua/options.lua
lua/packerInit.lua
lua/pluginList.lua
lua/plugins/luasnip.lua
lua/plugins/telescope.lua
lua/theme.lua

install.sh: Run PackerSync from script after install too
```
as the corresponding code for that was removed from init.lua
```
init: Asynchronously load filetype and syntax
```
lots of improvement for startup time
```
Fix formatting | Misc
```
* fix formatting in pluginList, luasnip
* don't use pcall on highlights
* sync and compile fzf and media files only when the error occurs, add a
help text telling tbe user to restart neovim
```
packerInit: Clone packer at opt path as we are lazy loading
```
move packadd to packerInit
```

Even faster startup time | Fix formatting | Misc

---

install.sh
lua/mappings.lua
lua/utils.lua

Hi all,
improvements for terminal integration below! :)
- There seems to be some config confusion between buffers & tabs, see [buffers vs. tabs](https://github.com/mhinz/vim-galore#buffers-windows-tabs), this removes tab functionality that wasn't properly configured.
- Improve terminal functionality
- Improve terminal section of install script
**tl;dr:** monkey installs & uses terminals better now
------------------------------------------------------------------------------------------------------------------------------------------------------
**Tabs, buffers & terminals** - [mappings.lua](https://github.com/siduck76/NvChad/compare/main...G-Rowell:dev-terminalAndScript?expand=1#diff-a0766e1a2e02b2ea4daca632884f3b3da5484029148d88b3012ba2b14efcbef6)
-  Use proper neovim functions see note …

Fix buffers/tab terminal issues, improve terminal install scripting

---

lua/plugins/lspconfig.lua

Added:
1. A glyph that's just a little but smaller. Small enough to be able to distinguish from other in-line lsp diagnostics.
It looks like this:
Some others that people might like could be:
```
ﱢ  ﱡ  
```
(if they are not displayed properly is because you need a patched nerd font)
2. Suppressed error messages from language servers. Especially useful for `diagnosticls`.

Lang servers error suppression and better "publish diagnostics" glyph

---

init.lua
lua/options.lua
lua/utils.lua

This PR disables all builtin plugins because it wasn't being done before and also securely calls all of nvchad's modules.
**Why do we need to securely call the modules?**
The secure call feature that this PR implements assures that users will get a clear trackback to where the issue originated. This is an example of what the error message looks like if `x` given module fails to load:
As you can see it's easy to identify what's causing the issue.
Furthermore, another _huge_ advantage secure calls have is that no matter if the module being required failed, the other will still be able to work with "what's left". This guarantees that no matter how high up the issue occurs the rest should still be loaded. For example:
If there was an error loading the `plugins.bufferline` module, then neither …

Securely call modules and disable all builtin plugin

---

lua/utils.lua

Hi all,
[fix for a bug I introduced](https://github.com/siduck76/NvChad/pull/167#issuecomment-883833117)
**Bug fix**
- Fix closing terminal with `<SHIFT> + x` that is the only buffer (and opened with `<CNTL> + t + t`
Now closes properly
Now terminals that are quit from within using `<CNTL> + d` no longer automatically close that term buffer, may fix later
- Also fixes the status line issue too
@siduck76 planning on having a wander through docs & posts regarding the terminal,
so feel free to pull this but I may work more
**tl;dr:** monkey made bug, monkey a8 bug

Fix term crash bug, no auto-close finished term anymore

---

lua/themes/javacafe.lua

[Relevant PR](https://github.com/siduck76/nvim-base16.lua/pull/2) in the `nvim-base16.lua` repo.

Added javacafe color scheme

---

lua/mappings.lua
lua/pluginList.lua
lua/plugins/others.lua

Use jdhao/better-escape.vim to handle jk as escape mappings
only for insert mode ( so also works on terminal too )
remove visual mode key binding, till we find a proper solution, because it is super annoying right now
Original pr here: https://github.com/siduck76/NvChad/pull/160
---
mappings: Allow moving the cursor through wrapped lines normally
This doesn't affect any other stuff like 10j or 10k

Use jdhao/better-escape.vim | Allow moving the cursor through wrapped lines normally

---

lua/mappings.lua

Hi all,
fixed a mapping error with `<CNTL> + t + t` for a new terminal buffer.
tl;dr: monkey fix bug

fix mapping error

---

install.sh

I tried installing it on my system and it failed mostly because the NvChad was by default installed to the `.config` directory. I use a custom dir for my `XDG_CONFIG_HOME` so I figured if anyone has the same issue this would be an easy way to have it not work for them, the fallback dir here is `.config` if the user has not set a custom one.

add XDG_CONFIG_HOME

---

install.sh

`/usr/bin/bash` and `/bin/bash` aren't guaranteed to exist on many systems, but `/usr/bin/env` is. This change makes the shebang line `/usr/bin/env bash`, so that it works on any modern *nix type system. Tested in macOS, Ubuntu and WSL.

Replaced 'bin/bash' with 'usr/bin/env bash' for better system compatibility

---

lua/highlights.lua
lua/mappings.lua
lua/options.lua
lua/packerInit.lua

Instead of a having a bunch of:
```lua
vim.opt.myopt = true
vim.opt.test = {"smth"}
vim.opt.run = false
```
Let's use:
```lua
local opt = vim.opt
opt.myopt = true
opt.test = {"smth"}
opt.run = false
```

Fix: set local variables for commonly used `vim.*` stuff

---

lua/chadrc.lua
lua/mappings.lua
lua/options.lua
lua/pluginList.lua
lua/plugins/nvimtree.lua
lua/plugins/toggleterm.lua

Hi all,
This is some cool work that was started off by @curtainp!
So credit to them!
- Installed the [nvim-toggleterm.lua plugin](https://github.com/akinsho/nvim-toggleterm.lua)
- Setup various keybinds / autocommands for it
-- `<LEADER> + h` for a horizontal terminal
-- `<LEADER> + v` for a vertical terminal
-- `<LEADER> + w` for a window terminal    (this one is my fav)
- Improved the statusline hiding by adding a `chadrc.lua` table, `chadrc.ui.hidden_statusline`
-- now we can easily hide the statusline of any filetype!
- Make the horizontal, vertical & terminals separate maybe?
-- `nvim-toggleterm.lua` does provide this functionality already, do we want to wrap it?
*tl;dr*: monkey uses terms better

WIP - Added toggleterm, based upon curtanips work

---

lua/chadrc.lua
lua/mappings.lua
lua/plugins/toggleterm.lua

Hi all,
Currently this creates 3 persistent terminals for you to use,
you can do this all easily with native [nvim-toggleterm.lua](https://github.com/akinsho/nvim-toggleterm.lua) functionality, but this is just a wrapper for your 3 `main` terms.
- `<leader> + w` for a window term (IE. full screen)
- `<leader> + h` for a horizontal term
- `<leader> + v` for a vertical term
These are each three distinct & persistent terminals
- `JK` (not `jk`) to escape mode & hide the term
- `jk` still exits terminal mode (not changed, just noting this here)
- currently this saves each of the three terms as global vars, we'll likely still have to do this....but we could format it in a nicer way
-- maybe have a global nvChad table, which can contain the theme, these 3 terms...etc.
- I think it may be …

Now have 3 separate terms, window, vert & hori, renamed some variables

---

lua/chadrc.lua
lua/pluginList.lua

In the following files I have done the following:
- `chadrc.lua`: in the file the plugins were set to false it may confuse the user to that false is disable. So the solution was change it to true
- `pluginList.lua`: In this file I have changed  the following function to not `disable = not plugin_status.galaxyline`. This solves the confusion and doesn't causes and error.
The following change was tested by changing the plugin to false and it uninstalled the plugin. Changed the value to true and it installed the plugin.

refact: move false to true in plugins and change disable to 'not' so that the user does'nt be confused

---

lua/chadrc.lua
lua/default_config.lua
lua/options.lua

Hi all,
This is a small PR to add:
- the `relativenumber` option to `chadrc.lua` & `default_options.lua`, default is `false`
-- an autocommand to enable hybrid (number + relative) numbers in normal mode, and absolute (number) in insert mode, default is comment out
- imrpoved/fixed the statusline option to work with `NvimTree` (works with terms now too, though not enabled by default)
G

added relativenumber option & statusline option

---

lua/plugins/telescope.lua

- Update `path_display` default config of telescope. It will display the filename of matched results first, so we can inspect search the results better, especially with long file name.  Related document can be found [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L175).

chore(telescope): update default path_display config

---

lua/chadrc.lua
lua/default_config.lua
lua/plugins/dashboard.lua

Hi all,
- The `Dashboard` had an outdated binding (said `<leader> + s + l`, instead of `<leader> + l` for loading a session
- Fix an issue where one cannot enable the statusline in terminals, this is a hack for a proper solution
-- @Akianonymus, think we need to consider how to handle this issue
I checked all the other binds in the `Dashboard`, they seem correct
G

fix Dashboard docs, fix default_config issue

---

lua/utils.lua

Hi all,
- the `close_buffer` lua function would exit if the current buffer was unlisted, this prevented closing buffers like `help buffers`
- this has been `hotfixed` IE. revisit this later
- initial testing makes it seem reasonable, but it is not thoroughly tested,
- it's still a big improvement on a breaking change I made (sorry....), so I think this should be pulled in
---
- previously there was no way for the user to enable the statusline on terminals, as it was enabled in `default_config`
- this was fixed by a restructure of the `hide_statusline` table to use boolean flags,
- set an entry like so
- `terminal = true,`  (filetype = true) true is hide, false is show
---
G

Improve statusline config & hotifx close_buffer issue

---

README.md

Here's a quick demo of how easy it is to quickly get a feel for NvChad without messing with any of your current configuration
[![asciicast](https://asciinema.org/a/RxE9FOZg1p8AgEQkAhPb6tGMj.svg)](https://asciinema.org/a/RxE9FOZg1p8AgEQkAhPb6tGMj)

Added a command to quickly spin up a working NvChad docker container

---

README.md

Contribute link points to dead link https://nvchad.netlify.app/docs/Contribute. It looks like it should point to https://nvchad.netlify.app/contribute/
Steps to Test
- click Contribute link in this fork/branch's readme: https://github.com/charliestrawn/NvChad/tree/fix-install-link-readme#nvchad

fix contribute link in readme

---

lua/plugins/init.lua

closes #356 
Adds some fugitive commands make sense to load for. Commands for viewing diffs and for writing. Most commonly used functionality is under `Git` (ie `:Git commit`)

commands to load fugitive

---

lua/chadrc.lua
lua/core/mappings.lua

I love how these configs are getting better every day!
There was no easy movements between terminals, vimtree nor split opened buffers. With this change, you can move between all of them easily without the mouse by pressing `Ctrl + h` ; `Ctrl + l` ; `Ctrl + j` ; `Ctrl + k` . I thought it should be having it by default.

Changed mappings to move between windows/terminals with Ctrl+h,j,k,l

---

lua/plugins/configs/bufferline.lua

Fixes a small issue with coloring when `diagnostics = "nvim_lsp"` is set to enhance color consistency.
Before, the text background for the unselected tab (evaluator.scm) with a diagnostic does not match the tab background:
After, text background matches the tab background:
There may be more work to make this fully consistent (there are info diagnostics, etc), but this is a start.

Set colors for lsp diagnostics

---

lua/plugins/configs/others.lua

I wanted to set up indent line `show context` and it wasn't working properly.
Your original packer definition of this plugin is using `config`. I think that defining global variables, ie `vim.g.indent_line_do_something` needs to be declared within the packers `setup` function (run before the plugin). 
I went through their docs and saw that they have a setup function instead, and that's usually better than riddling the global scope with variables.

fix(plugin): indentline using config instead of setup

---

lua/core/hooks.lua
lua/custom/init.lua
lua/plugins/configs/lspconfig.lua

Hey again.
The issue in #372 does not really get solved by the current hook system, as it only adds the ability to run additional setup during NvChad initialization/commands, not modify the existing stuff.
This is something I was originally wondering if I should add to that original PR but decided against it, as I wasn't sure it is a feature that is generally useful enough, but well given that it could solve some issues, here it is for discussion:
So this introduces hook based overrides.
Of cause `chadrc.lua` should be the main place to configure NvChad, but if all options of all plugins was exposed it would become so extensive that it would be really hard to maintain, so I get having some values be set to something that just works for most people makes sens.
The idea here is that for the …

feat: Hook based option overrides

---

lua/plugins/configs/others.lua

https://github.com/ray-x/lsp_signature.nvim/commit/e5922339e4a48773dded456a244be9130572ddfa
use_lspsaga option deprecated.

use_lspsaga deprecated, see lsp_signature upstream commit

---

lua/core/autocmds.lua

**PATCH** : This patch aims to close NvimTree (if open) in case the user quits the last existing buffer.
**ASSUMPTION** : It has been assumed that the user would **like to quit** out of nvim as soon as the **last buffer is closed**. If the file explorer is open in this situation it wont close and the user needs to manually exit with `:q!`
**DEMONSTRATION :**
Pre-patch behavior 
https://user-images.githubusercontent.com/65299153/132296060-7193e922-0aa7-4205-90d9-b53a59c9196a.mp4
> Notice when only one buffer is left and it is closed NvimTree is still open after closing it.
The expected behavior would be that NvimTree also closes, instead the user has to use `:q!` to quit out. Repeating this behavior multiple times becomes very annoying.
Patched behavior …

[Patch] Auto close Nvimtree incase of quitting last existing buffer

---

lua/plugins/configs/statusline.lua

Feline changed their config format and deprecated the old one (see https://github.com/famiu/feline.nvim/commit/8c809b2416fa6773719f3c391eb7b124d67c866e). This PR updates NvChad's config, solves issue #435

Update feline config to new format

---

lua/plugins/init.lua

If you want to use this plugin with Neovim 0.5, please use the 0.5-compat branch. Be aware though that most improvements will require neovim nightly.
https://github.com/nvim-treesitter/nvim-treesitter

feat: Move treesitter branch to compat-0.5

---

README.md

It's kind of annoying to see `nvim-tree` image/screenshot over and over again. If it was intentional, you can close this PR 👀

Remove duplicate nvim-tree images in readme

---

lua/plugins/configs/telescope.lua

Just a minor tweak to telescope config
1. Added node_modules to file_ignore_patterns
It's just annoying to see the node_modules folder in telescope, and it doesn't always match correctly when there are too many files.

ignore node_module folder in telescope

---

README.md

With the new docs I changed the links in the Readme. The link in the about section of the repo also needs to be updated, but its not something I can do.

fix: Replace Website Link in README.md

---

.gitignore

- since it's pointless to track user specific files, added the custom dir to the ignore list except for the example files.

fix: ignore unwanted files in custom dir

---

lua/plugins/configs/nvimtree.lua

Options are currently being migrated into the setup function, you need to run require'nvim-tree'.setup() in your personal configurations. Setup should be run in a lua file or in a lua heredoc (:help lua-heredoc) if using in a vim file. Note that options under the g: command should be set BEFORE running the setup function.
I've moved the ones that have been migrated

Moved the setting into setup for Nvimtree

---

lua/core/default_config.lua
lua/core/utils.lua

Ahhh, sorry
I think I must've missed this single var rename inside of `default_config`,
`plugin` when it should be `plugins`.
The rest of the changes are all pretty much comments.
---
This should not impact any users at all,
and this will only fix 1 bug with `"['mappings']['plugins']['esc_insertmode']",`
as it was referencing `plugin` not `plugins`
G

fix: `default_config` var `plugin` -> `plugins` instead

---

init.lua

Why do we have a table to require a single module. We had this when we had plugins, colors etc. 
But we only have one module now. So why bother a list and looping through for a single module ?

chore: Clean init.lua

---

lua/core/default_config.lua
lua/plugins/init.lua

I don't use file browsers in vim (just fuzzy finders), so I was looking to disable nvimtree. I was surprised that the config didn't support disabling it, like you can with other plugins. I assume this was an oversight, but correct me if I'm wrong and it's required somehow.

add config option to disable nvimtree

---

lua/plugins/configs/nvimtree.lua

Taken directly from [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) readme

feat(nvimtree): exclude terminal from window picker

---

lua/plugins/configs/others.lua

LSP diagnostic icons don't show correctly in the gutter. Line numbers are also not colored correctly:
Fixed (reference: [nvim-lspconfig README](https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#change-diagnostic-symbols-in-the-sign-column-gutter)):

fix: LSP diagnostic icons

---

lua/plugins/init.lua

User/organization named `feline.nvim` does not exist.
It should be `feline-nvim`.

fix typo in feline repo

---

.github/README.md

nvim-lspconfig now requires 0.6+, so the config will break on 0.5.

raise the minimum version to 0.6+

---

lua/core/mappings.lua

Resolves #682 
Prior to this change, searches through large repositories would include
files within the .gitignore, resulting in long search results and many
useless results.  This change results in `find_files` respecting
.gitignore and `find_hiddenfiles` instead being an exhaustive search over
all files within the current directory.

Feat: Remove no_ignore option from Telescope find files

---

examples/example_init.lua

Hi! I'm new to NvChad.
This comment...
https://github.com/NvChad/NvChad/blob/de9b702f0ed6ec60795156ccb94101774be743e2/examples/example_init.lua#L21
... made me go double check which name is correct ...
https://github.com/NvChad/NvChad/blob/de9b702f0ed6ec60795156ccb94101774be743e2/lua/core/hooks.lua#L4
Hope this saves someone else a few minutes!
```diff
- install_plugin
+ install_plugins
```

fix typo in example_init.lua

---

lua/core/utils.lua
lua/plugins/configs/statusline.lua

neovim/neovim#16745 which was merged into master a bit ago causes errors on opening nvchad due to no longer accepting nil in numerous api functions. The statusline config made use of this implicit conversion and I changed it to convert nil to 0 prior to function call.  A side effect of the implementation of the neovim commit is that '%' no longer can be used to refer to current buffer. This may be changed slightly later as I have seen a few commits over the last few hours updating related functions elsewhere in neovim, but I wouldn't count on it and these edits are necessary to keep nvchad running on up to date builds, and are the 'correct' implementation regardless of what other inputs they decide to reallow.

fix errors thrown by implicit conversions in latest neovim build

---

lua/core/mappings.lua

Woops
I mixed up the argument ordering in #717

hotfix to :Telescope command flag order

---

lua/plugins/configs/statusline.lua

A while ago I wanted to override the default NvChad statusline with a couple of changes, and quickly found that adding any new component, or removing any component would require changing the number in the insert function of every subsequent component in the corresponding area of the statusline, namely being the left (1), middle(2) -but only one component so non-issue really, and right(3). Now there are quite a few components in the NvChad statusline and this quickly became extremely cumbersome. While my statusline now differs greatly from NvChad, the flexibility of my method has been invaluable in customizing it for clarity and time saving purposes so I felt updating it here might be a benefit to many individuals.
The NvChad statusline is appealing to many users and has some functionality …

Statusline Rewrite for Clarity and Customizability

---

lua/core/utils.lua
lua/plugins/configs/bufferline.lua
lua/plugins/configs/cmp.lua
lua/plugins/configs/icons.lua
lua/plugins/configs/nvimtree.lua
lua/plugins/configs/others.lua
lua/plugins/configs/statusline.lua
lua/plugins/configs/telescope.lua
lua/plugins/configs/treesitter.lua
lua/plugins/init.lua

- bufferline.nvim (bufferline)
- comment.nvim (nvim_comment)
- gitsigns (gitsigns)
- indent-blankline.nvim
- LuaSnip (luasnip)
- lsp_signature (signature)
- nvim-autopairs (nvim_autopairs)
- nvim-cmp (nvim_cmp)
- nvim-colorizer (nvim_colorizer)
- nvim-lspconfig (nvim_lspconfig)
- nvim-tree (nvim_tree)
- nvim-treesitter (nvim_treesitter)
- nvim-web-devicons (nvim_web_devicons)
- Telescope (telescope)
- better-escape
- dashboard-nvim
-  lspconfig
-  lsp_handler
_**Note: See the nvim_cmp section of the below example for how to override lspkind_icons as part of cmp**_
```
default_plugin_config_replace = {
telescope = { defaults = { prompt_prefix = " ?  "}},
nvim_treesitter = { highlight = { enable = true}},
nvim_autopairs = {},
nvim_web_devicons = {
override ={
lua = {
icon = "L",
name = …
```

Add/Remove/Overwrite individual keys in NvChad setups

---

lua/core/default_config.lua
lua/plugins/configs/cmp.lua
lua/plugins/init.lua

I thought many users dont use snippets, so they would like to disable it.
This option remove snippets plugins from order of lazy loading and remove it use from cmp mapping

feat: Add config.plugins.status.snippets to enable/disable snippets

---

lua/core/options.lua

This just sets shada to none so it isn't read during startup, and then sets it to the normal location and reads it after startup. For some users the difference may be negligible, but many plugins will write to shada and over time command history etc fills up and this can save a lot of time.
Once, before discovering this, I saw shada took like 15ms to load and I checked it, and it had over 13k lines.... I had to just delete the file to restore startup times, this should avoid situations like that.
Even having cleaned it pretty recently, this change saves me around 3-4ms for each startup.

improve startup time with shada load deferral

---

lua/colors/highlights.lua

This fixes the acid blue cursor when using alacritty. Fixes #200

fix acid blue cursor

---

lua/core/utils.lua
lua/plugins/init.lua

@siduck @Akianonymus  This is a solution which I should have thought of ages ago during the dispute around having a labeled plugin table or not. This PR leaves the current table unchanged and therefore "pretty" as it is, but the functions for merging changes from chadrc are vastly simplified.
I've been having issues with an error message about using the same plugins multiple times on vanilla NvChad with just a basic chadrc, and the current logic for adding and removing plugins, while improved since the first iteration, remains somewhat difficult to debug and therefore is not ideal. These changes fix all that.
Notable improvements include:
1. If the user has a plugin in their custom plugin table which is already in the default table, their plugin will automatically take the place of the …

improve method of adding and removing plugins

---

lua/core/utils.lua
lua/plugins/init.lua

In the last PR , while moving code from init.lua to utils I forgot to declare a var as a local and left the wrong one was referenced in init.lua without throwing an error because of it, which may have been causing some issues. This fixes it.
Also see #824 for an unrelated, but probably larger, issue that I discovered while debugging this one.

fix global variable causing issues

---

lua/core/autocmds.lua
lua/core/default_config.lua

While taking a look at #829 and #824 I realized my local fix for toggleterm would show up as a change and it was kinda annoying. This is a quick fix allowing the user to disable the autocmd which makes nvchad not place nice with term plugins.
Really only temporarily needed until I have time to fully implement #811

fix autocmd breaking term plugins

---

lua/core/utils.lua

Fixes https://github.com/NvChad/NvChad/issues/824
This allows 'install' in chadrc to be a string, meaning that the plugin table won't be loaded every time the config is. This should give a light performance boost as well as fixing the breakage caused by requiring the config from the plugin table.
To prevent this from being a breaking change, table values and require("some.user.table") are still accepted. Users who wish to reference plugins.status from their config table, or boost their config's efficiency should use install = "some.user.table" instead though.

fix for getting config settings from plugin table

---

lua/plugins/init.lua

TreeSitter recommends running `:TSUpdate` after update with TS or on (re-)installation of Treesitter. Reference example recommended by TS: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation

feat: Run `:TSUpdate` on TS Install / Update

---

lua/plugins/init.lua

https://github.com/NvChad/NvChad/pull/838
> TreeSitter recommends running `:TSUpdate` after update with TS or on (re-)installation of Treesitter. Reference example recommended by TS: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation

feat: Run :TSUpdate on TS Install / Update

---

lua/core/mappings.lua

When trying to replace-paste text at the end of a line results in the letter before the to be replaced text to be moved at the end of line after the replacement text. See, #844 for more details.
This is a known issue with the used mapping for paste on visual select, see https://vim.fandom.com/wiki/Replace_a_word_with_yanked_text#Mapping_for_paste . That same page also offers an alternative mapping which solves this issue. 
The mapping was tested using five different use cases, see https://github.com/NvChad/NvChad/issues/844#issuecomment-1053533198 for additional information on this test.

fix for (#844) Replace-paste at end of line incorrect

---

lua/plugins/init.lua

Currently if you open neovim on a file that doesn't yet exist or have any content (for example: nvim newfile.lua') treesitter will not load until you quit and reopen the file. This makes it so that it will still load on the file if the extension matches an install parser, no write and restart needed.

fix for treesitter not loading on creating new file

---

lua/plugins/configs/lspconfig.lua

Features Added:
- No prompt for null-ls required (2 formaters)
Reasoning:
Every time I execute `<leader>fm` it prompt asking which of the, in my case, 2 formatters I'd like to use. In most if not all case it's the previously configured through null-ls formatter.
Other:
message @ 4e68ee06
```
add `client.resolved_capabilities.{document_formatting,document_range_formatting}` to on\_attach of lspconfig in order to eliminate null-ls prompt for 2 formaters. Not tested with more formatters like in python, I'd say that then it'll prompt still.
Signed-off-by: Daniel Boll <danielboll.academico@gmail.com>
```
I don't know if this should be considered going to the upstream repo as null-ls isn't officially supported within NvChad, although suggested.
Best Regards,
Daniel Boll. :flower_playing_cards:

fix(null-ls): stop null-ls prompt for multiple formaters

---

lua/plugins/configs/cmp.lua

Some snippets support set a default value for the snippet body. This support use <Tab> to jump to the next part without changing the default values.

Luasnip support <Tab> jump between snippets in visual mode

---

lua/plugins/configs/lspconfig.lua

Hello,
This PR aims to expose the `on_attach` function to be able to configure plugins in custom folder when using `Packer` callbacks.
One can just `require('plugins.configs.lspconfig').on_attach` to use it when lazy configuring Lsp plugins.
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

Exposing on_attach to configure plugins in custom

---

lua/core/mappings.lua

When you are in select mode and enter "j" or "k", it will not replace the selected area, but will move the cursor.
According to this table from the vim docs, the new mapping will work in all other cases.
```
Mode  | Norm | Ins | Cmd | Vis | Sel | Opr | Term | Lang | ~
Command        +------+-----+-----+-----+-----+-----+------+------+ ~
[nore]map      | yes  |  -  |  -  | yes | yes | yes |  -   |  -   |
n[nore]map     | yes  |  -  |  -  |  -  |  -  |  -  |  -   |  -   |
[nore]map!     |  -   | yes | yes |  -  |  -  |  -  |  -   |  -   |
i[nore]map     |  -   | yes |  -  |  -  |  -  |  -  |  -   |  -   |
c[nore]map     |  -   |  -  | yes |  -  |  -  |  -  |  -   |  -   |
v[nore]map     |  -   |  -  |  -  | yes | yes |  -  |  -   |  -   |
x[nore]map     |  -   |  -  |  -  | yes |  -  |  - …
```

Fix j -> gj mapping.

---

lua/plugins/configs/nvimtree.lua

Currently, changing any of the options stored in vim globals has no effect. This can be easily reproduced by attempting to disable folder icons by changing the code in the default file like so:
```
g.nvim_tree_show_icons = {
folders = 1,
files = 1,
git = 1,
}
```
to 
```
g.nvim_tree_show_icons = {
folders = 0,
files = 0,
git = 1,
}
```
The icons will still be there on restart. With the change to move the setting globals above the require statement in this patch, the above code functions properly.

fix nvimtree vim globals not having any effect

---

lua/colors/init.lua
lua/core/default_config.lua

With this pr, users could use any themes they want. Specifically, 
1.  add themes to `userPlugins`
```lua
--  custom/plugins/inited.lua
...
{ "local/path/to/mytheme" }, -- local
{ "Iron-E/nvim-highlite" }, -- remote
...
```
2.  add colors file (i.e. `custom/colors.lua`) in format of [this](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/hl_themes/aquarium.lua)
3.  set colors and theme in `chadrc.lua`
```lua
-- custom/chadrc.lua
...
M.ui = {
theme = "mytheme",
-- theme = "highlite",
colors = "custom.colors",
}
...
```
Related to #631.

feat: support themes other than defaults

---

lua/core/default_config.lua

Chadterm will no longer overlap with nvimtree by default, but people who want to use the old splitting method or others can do so by setting the horizontal and vertical fields in options.terminal.location from chadrc.
NvChad/extensions#11 has been PR'd and fixes the issues with bufferline and nvimtree mentioned in #925

add new location option for chadterm to default config

---

lua/core/autocmds.lua
lua/core/default_config.lua

Description in title. Discovered when trying to test out global statusline that statusline_hide() always sets laststatus regardless of user options, making global statusline impossible to enable. 
I I thought about adding a specific global option, but that's up to you @siduck, since I know you are trying to keep down bloat. Regardless, there should never be a case where we have an autocmd set an option and not have an option to disable it.

add disable option for statusline hide autocmd

---

lua/plugins/init.lua

By default packer tries to use "master" for the branch of any plugin that doesn't have a branch explicitly defined. However, the bufferline authors recently renamed their default branch from "master" to main. Thus, packer will work fine with bufferline for any new clones, but it will fail to update for anyone who had the old branch name "master" set.
See also: https://github.com/wbthomason/packer.nvim/issues/86

override default branch for bufferline

---

lua/core/utils.lua

Currently NvChad silently fails when some newbie screws up their `custom/chadrc.lua`, and because they're a newbie they either uninstall NvChad, revert to the base config, or stay up all night debugging in a language they don't understand (yet)  😅 
* Explicitly check if chadrc.lua exists and is readable (same as is done for `custom/init.vim`
* Don't assume the only way `require "custom/chadrc.lua"` can fail is that the file doesn't exist (as was implied by var names/lack of alternative error handling)
* Provide user with a more useful message when return type is wrong
* `thisIsntJava` and everything else is using `snake_case`, so `chadrcExists` -> `chadrc_exists`
The previous behavior suppresses valuable error information and simple syntax error into a multi-hour debug-athon Related (last …

Typecheck return value of chadrc; propagate errors

---

lua/plugins/configs/nvimtree.lua

The NvimTree has moved the option "nvim_tree_indent_markers" to setup in their latest version.
kyazdani42/nvim-tree.lua#1134

fix: move option "nvim_tree_indent_markers" to setup

---

lua/plugins/configs/lspconfig.lua

The [lspconfig documents](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion#nvim-cmp) don't suggest using `omnifunc` when using `nvim-cmp`:
> If you are using nvim-cmp do not use neovim's built-in omnifunc as it cannot support the additional completion items returned from servers due to the capabilities enabled by nvim-cmp.

chore: disable omnifunc

---

lua/plugins/init.lua

See #983
Also the `opt` key is implied by the `setup` key, so it is not needed.

New try of #983, as well removing unnecessary opt key

---

lua/core/utils.lua

`vim.keymap.set` mappings are not recursive by default (remap = false). actually `vim.keymap.set` ignores `noremap` and overrides its value based on the value of `remap` which is false by default (as stated [here](https://neovim.discourse.group/t/which-one-has-more-precedence-noremap-or-remap/2526/2))

refactor: remove `noremap` from `utils.map`

---

lua/core/autocmds.lua

The first one highlights the yanked text for 200 ms so we can we what is yanked.
The second one enables built-in spellchecking in text, markdown, and gitcommit files.

feat: add more autocommands

---

lua/plugins/configs/cmp.lua

This PR fixes issue #1031 that arose from commit 08e9ab363e3486034db0de4a42992c86bfedfb2c, causing tab autocomplete to not work after calling Telescope.

Update cmp.lua, fixes tab autocomplete not working after calling Telescope

---

lua/plugins/configs/lspconfig.lua

`client_capabilities` is now deprecated, `server_capabilities` does the same thing.

Fix deprecated client_capabilities usage

---

lua/core/mappings.lua
lua/plugins/configs/whichkey.lua

@siduck As the title suggests, I fixed some existing keymaps, added ones for which-key and added a feature where users can now set `mode_opts` per keymap. This is important for registering expressions or similar, however setting `mode_opts` is completely optional.
These are some of the `mode_opts` values that can be set:
```lua
-- IMPORTANT: `mode_opts` values will apply to all key mappings in `M.<YOUR_KEY_MAP_LIST>`
mode_opts =  {
buffer = nil, -- Global mappings. Specify a buffer number for buffer local mappings
silent = true, -- use `silent` when creating keymaps
noremap = true, -- use `noremap` when creating keymaps
nowait = false, -- use `nowait` when creating keymaps
-- and more ...
}
```
Before it was not possible to add expressions or alter any other options on an extension basis. …

feat: added which-key keymaps, fixed telescope keymap & custom "mode_opt" for keymaps

---

lua/core/utils.lua

@siduck The issue when there is no `M.mappings` table defined in `chadrc` (mentioned in here https://github.com/NvChad/NvChad/commit/1bc1d9c52af3ad6f2d12ebc68dca2db7fa02dd54) is now handled

fix: handled bug when no mappings table was set in chadrc

---

lua/core/utils.lua

@siduck This is just a small fix becuase disabled bindings showed up in which-key again. Also tested with fresh NvChad installation.

fix: remove disabled maps from which-key popup (again)

---

lua/core/utils.lua
lua/plugins/configs/whichkey.lua

@siduck Which-key group names can now be set properly using `M.groups` in custom mappings. Before, the group names would sometimes randomly not be set. I also refactored some minor things. This has been tested with a fresh NvChad install & which-key uninstalled + `nvchad.no_Which_key()`.
Before:
After this PR:

fix: which-key group names can now properly set with M.groups & refactoring

---

lua/plugins/configs/cmp.lua

Am I the only one who thinks replacing the next word with the confirmed cmp suggestion is weird and annoying? Usually, we use cmp to "add" text not remove it.

fix(cmp): change the confirmation behaviour to `Insert`

---

lua/plugins/configs/cmp.lua

Commit `fae808a2bca079ea9454f33cb1e2db81c59e102b` for the `nvim-cmp` plugin removed the `has_scrollbar` breaking how NvChad hides the scroll bar.  As a result, the scrollbar is visible when there are more menu items than the size of the window.
See the change [here](https://github.com/hrsh7th/nvim-cmp/commit/fae808a2bca079ea9454f33cb1e2db81c59e102b).
This proposed change wraps the call to `window:info` and sets the `info` table's `scrollable` property to `false` before returning the table to the caller.
This most likely went unnoticed because nothing calls `has_scrollbar`, so there was nothing to trigger an error.

fix: update hide scrollbar logic to work with cmp

---

lua/plugins/configs/whichkey.lua

Hi, when I was creating my own configuration, I found this problem here.
According to `lua/plugins/configs/whichkey.lua`  we can override the config of the default `whichKey` plugin options.
```lua
M.plugins = {
override = {
["folke/which-key.nvim"] = {
mode_opts = {
-- support add keymaps to visual block mode
x = {
mode = "x" 
}
}
}
}
}
```
Then in `custom.mappings` add the following section:
```lua
M.general = {
x = {
["<A-h>"] = { "<cmd> lua print('just a example') <CR>", "example text" },
}
}
```
This does not work, because the override happens only after calling `wk.register`:
https://github.com/NvChad/NvChad/blob/d264c3c8e11a1acde34f2f874f5bd353a8772d2f/lua/plugins/configs/whichkey.lua#L65-L79
So overriding the options won't change anything.  To fix this problem, we could just move …

fix: override options before register keys

---

lua/plugins/init.lua

Very hard to describe using words so here is a video
https://user-images.githubusercontent.com/56817415/169878130-9d3e5917-3a39-47fe-8760-d5a69cfa0ede.mp4
Minimal config used to reproduce the bug:
`/tmp/min.lua`
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/min/site]]
local package_root = "/tmp/min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
require("packer").startup {
{
"wbthomason/packer.nvim",
"kyazdani42/nvim-web-devicons",
"akinsho/bufferline.nvim",
"akinsho/toggleterm.nvim",
"goolord/alpha-nvim"
},
config = {
package_root = package_root,
compile_path = install_path .. …
```

Load nvimtree with alpha so ignore_ft_on_setup actually works

---

lua/core/mappings.lua
lua/core/utils.lua
lua/plugins/configs/lspconfig.lua
lua/plugins/configs/whichkey.lua

@siduck I moved the LSP mappings to `lspconfig.lua` and added some helper functions to ignore specific mappings, when the map function is called from a set of predefined file paths. This is done by listing them in the new `ignore` key in the plugin mappings that can hold a list of paths, which will cause those maps not to be applied when the map function is called from within those files. The nvim config location (i.e. `~/.config/nvim`) is the base path here, so all ignore entries can start from here (e.g. `/lua/plugins/configs/whichkey.lua` will cause the maps not to be set when the map function is called from within `whichkey.lua`). The issue we still have is that when registering the keys in `lspconfig.lua` we have to pass the options table, which I have (for now) simply copied from …

fix: moved lsp mappings to lspconfig to only be set on lsp attach

---

lua/plugins/configs/others.lua

For some reason, the `load_override` call for the luasnip setup was missing.

add option to override luasnip options

---

lua/plugins/configs/cmp.lua

Snippets suggestions comes more handy than language server suggestions in compeletion menu. so I filipped one line to give priority to luasnip. With this, snippets suggestions will apear first in completion menu.
I guess everyone would rather snippets first than lsp itself. 
BTW I didn't compare this with other editors, but I believe editors like vscode take advantage of this feature too.

change proiority of completion list in nvim-cmp

---

lua/ui/statusline.lua

When a project has multi lsp clients, the status line's lsp status just fetches the first one'name which is not correct exactly.
And this PR fix the bug.

fetch correct lsp name in status bar while existing multi actived lsp clients

---

lua/core/utils.lua

so we can use `require` even though it been lazy load like this.
```lua
local function override_cmp()
local cmp = require 'cmp'
return {
mapping = {
['<C-k>'] = cmp.mapping.select_prev_item(),
['<C-j>'] = cmp.mapping.select_next_item(),
["<Tab>"] = cmp.mapping(function(fallback)
local copilot_keys = vim.fn['copilot#Accept']()
if copilot_keys ~= '' and type(copilot_keys) == 'string' then
vim.api.nvim_feedkeys(copilot_keys, 'i', true)
elseif cmp.visible() then
cmp.select_next_item()
elseif require("luasnip").expand_or_jumpable() then
vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
else
fallback()
end
end, {
"i",
"s",
}),
}
}
end
M.override = {
["hrsh7th/nvim-cmp"] = override_cmp,
}
```
#1201

feature: make override can be a function

---

lua/core/utils.lua

In order to ensure that plugin configuration that is overridden with a
function instead of a table is still merged with the default plugin
configuration, this commit splits up the if/elseif/else statement in
lua/core/utils.lua.
This is necessary as we want to take the resulting table returned from
the override function and merge it with the default_table before setting
up the plugin.
Fixes [this issue](https://github.com/NvChad/NvChad/issues/1239)

Fix Plugin Override Function Capabilities

---

lua/plugins/configs/others.lua

In configuration for nvim-autopairs code could run even if there was a missing plugin.
This code shows the problem
```
present1 = true
present2 = false
if not present1 and present2 then
print "false detected"
else
print "false not detected"
end
```
When you run this code it will print "false not detected".

added missing brackets

---

lua/plugins/configs/nvimtree.lua

Signed-off-by: Höhl, Lukas <lukas.hoehl@accso.de>
Nvim-tree introduced an option to dynamically increase and shrink the size of the drawn tree.  \
See https://github.com/kyazdani42/nvim-tree.lua/pull/1293.
I think this is something, that nearly everyone wants in their default config, which is why this PR enables this feature in the default config of nvim-tree.

feat(nvim-tree): enable adaptize size

---

lua/plugins/configs/nvimtree.lua

Enables the option for nvim-tree to automatically sync on filesystem changes.
For more information, see https://github.com/kyazdani42/nvim-tree.lua/blob/7a795d78fa2a102de197e81b85f5b1e6b5f366a3/doc/nvim-tree-lua.txt#L508
Signed-off-by: Höhl, Lukas <lukas.hoehl@accso.de>

feat(nvimtree): enable filesystem watcher

---

lua/core/options.lua

• problem: providers are incorrectly disabled
• why: providers must be disabled by
setting their global value to 0,
unlike default plugins.
• solution: disable built-in providers by
setting their values to 0
instead of 1

fix: providers are not disabled

---

.stylua.toml

The option has changed since https://github.com/JohnnyMorganz/StyLua/pull/330
Updating the other repos as well:
https://github.com/NvChad/nvim-colorizer.lua/pull/5
https://github.com/NvChad/nvterm/pull/14
https://github.com/NvChad/base46/pull/90
https://github.com/NvChad/extensions/pull/31

stylua: Replace `no_call_parentheses` with `call_parentheses`

---

lua/ui/lsp.lua

Re add focusable and cursor opts to signatureHelp windows.
This options were removed with "clean config | fix (#1225) (#1226)" (9dca3e) and since then the signature help randomly takes focus.
These options are enough to avoid <leader>ls float window to not be focusable, and thus I expect the signatureHelp window also won't be, but since I haven't found a repeatable way to reproduce the issue I can't be sure.

signatureHelp: don't capture focus

---

lua/plugins/configs/mason.lua

It should be `williamboman/mason.nvim` instead of `williamboman/mason`.

fix: meson.nvim override typo

---

lua/core/options.lua

[Lua filetype detection is enabled by default in neovim nightly](https://github.com/neovim/neovim/pull/19216) so we don't need those two options. The reason we can't simply override them in `custom/init.lua` is that setting any value to `did_load_filetypes`, completely disables filetype detection (and therefore syntax highlighting) and this may confuse people that use neovim nightly. I know NvChad doesn't officially support neovim nightly but people may want to try it to see the new features and this PR makes their life easier. Also, you do a similar thing in `plugins/configs/lspconfig.lua` so I thought it's ok :)

fix(options): don't set `did_load_filetypes` in neovim nightly

---

lua/core/init.lua

Fix: mason installed binaries path appended to env.PATH when os is windows, the env path separator is ";".

Fix windows env path separator

---

lua/core/options.lua

Nvim now stores "session data" (shada, persistent undo, ...) in $XDG_STATE_HOME (~/.local/state)

fix(0.8): :bug: update session data dir in neovim nightly

---

lua/plugins/configs/others.lua

with a capital letter it doesn't work

'blankline' fix filetype_exclude mason

---

lua/plugins/configs/alpha.lua

users can adjust the padding between the top and the header, or the header and buttons.

fix: make paddings in the alpha layout can be overrided

---

lua/core/init.lua

I always use nvim in tmux and I often change my panes size.

Resize panes when vim window is resized

---

lua/core/lazy_load.lua

As Windows Syntax for Pipe is different, remove Pipe completely to make sure Gitsigns can be loaded when using on Windows Powershell

fix: Windows User cannot load gitsigns

---

lua/core/lazy_load.lua

As siduck removes the space from `vim.fn.system`, now the command is unusable.   
Re-add the space to make it work again

fix: gitsigns not loading anymore

---

lua/core/lazy_load.lua

Rn, even after loading gitsigns, we still have an autocmd that checks whether gitsigns is loaded or not, which is unnecessary.
This PR adds an augroup to that autocmd to stop the above from happening

remove gitsigns autocmd on gitsigns load

---

lua/plugins/init.lua

The which-keys plugin: https://github.com/folke/which-key.nvim#Plugins has other sub-plugins enabled by default including `Marks` and `Registers`.
`Marks` is triggered by the `` ` `` or `'` keys, and `Registers` is triggered by the " key. Note that neither of these keys require `<leader>` to be pressed, which is how the `which-key` plugin (if enabled) is lazy loaded in for now.
This leads to a strange behaviour where e.g. `"` or `'` only trigger the expected behaviour after `<leader>` is pressed at least once. To fix this I've added the aforementioned keys as eligible triggers to load `which-key` in.

fix: Added missing key triggers for which-key's sub-plugins

---

lua/plugins/configs/others.lua

Higher priority should be given to the user's own snippets

change snippets' priority

---

lua/core/mappings.lua
lua/plugins/configs/others.lua

Features Added:
- Buffer mappings for gitsigns
Reasoning:
The default settings from [ewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim#keymaps) does not include a default mapping for all gitsigns actions, also NvChad does not include this as well.

feat: add buffer mapping for gitsigns

---

lua/plugins/configs/cmp.lua

From the neovim doc,
In Vimscript:
`set completeopt=menu,menuone,noselect`
In Lua using `vim.o`:
`vim.o.completeopt = 'menu,menuone,noselect'`
In Lua using `vim.opt`:
`vim.opt.completeopt = { 'menu', 'menuoune', 'noselect' }`

config(cmp): correcting completeopt setup

---

.gitignore

If the user decides to install coc.nvim, he/she needs to create a `coc-settings.json` in the root of `nvim` (`:CocConfig` command). Since NvChad does not ship with coc.nvim, the file is exclusively customized and should be ignored.

Add coc-settings.json to .gitignore

---

.gitignore

Using `coc-lua` with `coc.nvim` will produce a `.luarc.json` when editing own custom configs that should be excluded from NvChad, since NvChad does not maintain its own `.luarc.json`

Add .luarc.json to .gitignore

---

lua/core/utils.lua

Avoids using pcall as a general catch all so that errors in one's custom chadrc aren't silently swallowed. 
Addresses issue #1690
Due credit to @ii14 for approach here..

ensure errors arent silently swallowed in custom chadrc if exists

---

init.lua

`mkdir -p` is assuming all users are using Unix, use builtin `vim.fn.mkdir` instead

Fix mkdir on windows

---

lua/plugins/configs/alpha.lua

At any time you can run the `:Alpha` command to revisit the dashboard, but this causes issues with the statusline.
One example is if you open the dashboard in a new tab and then open more new files in another new tab, especially without closing the dashboard, the autocmd's set up in the config don't toggle the statusline on and off at the right times.
This new revised logic checks the file type each time a buffer is departed from, or a tab is arrived at. It also stores the original value for `laststatus` in a unique `vim.g` location, and makes sure that is not overwritten.

Fix statusline toggle when re-visiting the dashboard

---

lua/plugins/configs/nvimtree.lua
lua/plugins/configs/others.lua
lua/plugins/init.lua

`kyazdani42` repo moved to `nvim-tree` repo.
So NvChad nedd to change referencing repository.
NvChad is outputting error at startup from Packer.nvim.
I fix the two reporitory reference.
[nvim-tree/nvim-tree.lua: A file explorer tree for neovim written in lua](https://github.com/nvim-tree/nvim-tree.lua)
[nvim-tree/nvim-web-devicons: lua `fork` of vim-web-devicons for neovim](https://github.com/nvim-tree/nvim-web-devicons)
This change fixes Packer.nvim.
I confirmed that the error in Packer.nvim disappears and nvim-tree and nvim-web-decicons works correctly after this changes.

【fix】 correct both of kyazdani42 repo into nvim-tree repo

---

lua/plugins/configs/nvimtree.lua

According to the wiki `ignore_ft_on_setup` is also deprecated, this solves the problem in #1755.
[https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup)

fix: nvim-tree deprecation notice (#1755)

---

lua/plugins/configs/nvimtree.lua

follow the latest nvim-tree option names
- [update_cwd → sync_root_with_cwd](https://github.com/nvim-tree/nvim-tree.lua/blob/02fdc262eba188198a7deb2117b3b996e6763d65/doc/nvim-tree-lua.txt#L497) 
- [update_focused_file.update_cwd → update_focused_file.update_root](https://github.com/nvim-tree/nvim-tree.lua/blob/02fdc262eba188198a7deb2117b3b996e6763d65/doc/nvim-tree-lua.txt#L530)

update nvim-tree option names

---

.gitignore

Currently, `cheatsheet.txt` is not added to the `.gitignore` file. This can cause issues. `cheatsheet.txt` is a file needed for [this](https://github.com/sudormrfbin/cheatsheet.nvim) plugin and unfortunately there isn't any option to change its path. This file should be excluded from the git repo, since NvChad doesn't maintain its own `cheatsheet.txt`.

Add cheatsheet.txt to .gitignore

---

lua/plugins/configs/lspconfig.lua

To easen chore of maintaining plugin spec for `nvchad_types`, I'll use Lazy.nvim types instead.
But to do that, I'd need to add lazy.nvim to be part of the workspace libraries

Add lazy.nvim to workspace library

---

lua/core/default_config.lua

The actual keybind is `<leader>t h` and not `<leader> t f `

Fix the "toggle theme" string in the default configs.

---

lua/plugins/init.lua

The base46 doesn't use the main branch for v1, but master.

fix: fix branch for base46 plugin
