NvChad/NvChad

install.sh

Script to automatically symlink config, install packer, and chosen language servers.

add install script

---

install.sh
lua/nvim-lspconfig/lua.lua

I mainly code in python so I added support for the python language server (pyls) in my personally dots, thought it wouldn't harm if everyone had access to them.

Add support for the python language server

---

install.sh
lua/bufferline/lua.lua
lua/nvim-compe/lua.lua
lua/nvim-lspconfig/lua.lua

- keybinds by lsp would be added whenever a language server is active.
- Added new keybinds for bufferline and keybinds for adding/deleting buffer.
- You can now autocomplete in insert mode using tab.

Added keybinds and some more stuff

---

install.sh

- added -p to mkdir to ensure the dir is created on clean installs
- added pip3 to pip validation

install.sh for init use and pip3

---

README.md
lua/compe/lua.lua

Added a small sign to indicate the snip better through the lsp and made a small change to the readme.md. Continuation of pull request #33

Better indication of snip in lsp and Readme change.

---

lua/lspconfig/lua.lua

Changes the default lsp letters to warnings. (cosmetic really)
For your review
before:
after:

Last cosmetic change

---

lua/nvim-lspconfig.lua

Fix unfinished String

---

lua/misc-utils.lua
lua/pluginList.lua
lua/whichkey.lua

PR for the addition of which key.
Change to misc-util with the addition of a timeout time of 500 ms. whichkey.lua contains the default settings for which key and can be modified
reference:
https://github.com/folke/which-key.nvim

Addition of which key

---

.github/workflows/stale.yml
.github/workflows/superLinter.yml
README.md

Added the following actions:
- stale issue managers that closes old issues/pr unless someone was assigned to it.
- linter for bash (lua keep on snagging on warnings)
Added a badge in the readme

Added 2 actions

---

install.sh

Changed script to rename nvim to nvim.bak instead of deleting it. No errors. Tested.

changed script to mv nvim to nvim.bak instead of deleting it

---

init.lua
lua/commenter.lua
lua/mappings.lua
lua/pluginList.lua

Added commenter support with `leader + / : CommentToggle`
Leader being the space key

Added commenter support.

---

lua/dashboard.lua
lua/misc-utils.lua

Things added:
- Added relative numbers option. It is currently commented in misc-utils.lua

Added relative numbers option and changed bookmark icon

---

lua/statusline.lua

small fix for galaxyline.nvim check git workspace condition mentioned [here](https://github.com/glepnir/galaxyline.nvim#default-provider-groups).

Fix Check Git Workspace Condition

---

install.sh

I removed -e flags of echoes as it not useful in the posix script.
echo -e in posix scripts just prints -e

removed -e flags in script

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Created a bug report template for easeness of understdanding the issue
- Created feature request template for features only.

created bug report template

---

.github/ISSUE_TEMPLATE/config.yml

created config.yml so that blank issues are not enabled

created config.yml in issue templates

---

.github/ISSUE_TEMPLATE/config.yml

added help links for NvChad in config.yml

updated config.yml

---

README.md

added more badges

---

lua/telescope-nvim.lua

fixes issue #115 . This has no errors. Update the config of telescope then restart NvChad. No errors.
I triple checked it.

Updated telescope config

---

README.md

Hello @siduck76 I made some changes in the readme.
I added logos.

Added logos and changed colors of readme

---

lua/pluginList.lua

In the commit of [commit](https://github.com/lukas-reineke/indent-blankline.nvim/commit/016fc91c2f34da9722c34c9970fb075faeafa786) the branch of lua was merged to master.

updated indent-blankline branch to master

---

lua/highlights.lua
lua/misc-utils.lua

Changes made:
- Changed relative number format option to current way.
- Fixed error #121

Fixed some things

---

lua/zenmode.lua

It seems that [TrueZen.nvim](https://github.com/Pocco81/TrueZen.nvim) options for configuration have been reworked. This is an updated file for the previous NvChad setup.

Update TrueZen.nvim configuration file

---

install.sh

* modify sed command to work in both gnu sed and mac os sed
https://stackoverflow.com/a/4247319
* use printf everywhere for more compatibility
* add some error checking

install.sh: Fix all shellcheck warnings | Misc improvements

---

lua/mappings.lua
lua/misc-utils.lua

Added:
- Made z prefix for zenmode mappings
- Added time out length setting in misc-utils.lua

Made some changes in mappings and settings

---

lua/themes/tomorrow-night.lua

Custom Tomorrow Night theme made from Tomorrow Night and Tomorrow Night Bright base16 themes.

Add tomorrow-night theme

---

lua/highlights.lua

Background colors for three themes in case terminal's background color is different.

Add background colors in case of different terminal colors

---

install.sh
lua/mappings.lua

install.sh changes: As much as i like automated scripts, they are a very high risk high reward thing. For that reason, i have refactored the script to check for potential edgecases that can mess up our existing stuff, obviously it's far from perfect but somewhere i guess.
About the second commit, i am assuming that was not the intended behaviour.

Refactor Install script | Fix a mapping bug

---

init.lua
install.sh
lua/mappings.lua
lua/options.lua
lua/packerInit.lua
lua/pluginList.lua
lua/plugins/autopairs.lua
lua/plugins/autosave.lua
lua/plugins/blankline.lua
lua/plugins/bufferline.lua
lua/plugins/colorizer.lua
lua/plugins/comment.lua
lua/plugins/compe.lua
lua/plugins/dashboard.lua
lua/plugins/gitsigns.lua
lua/plugins/icons.lua
lua/plugins/lspconfig.lua
lua/plugins/lspkind.lua
lua/plugins/luasnip.lua
lua/plugins/neoscroll.lua
lua/plugins/nvimtree.lua
lua/plugins/statusline.lua
lua/plugins/telescope.lua
lua/plugins/treesitter.lua
lua/plugins/zenmode.lua
lua/theme.lua
lua/utils.lua

install.sh: Don't ask for terminal shell when updating
---
[4/4] Refactor: install.sh: Don't handle packer | Misc
Handle a edgecase for config copying
---
[3/4] Refactor: init: Use async | Move theme stuff to theme.lua
third commit of refactor
perf improvements due to async
run packer sync if base16 not found
this is not perfect error handling for initial run, but something
handle require errors
---
[2/4] Refactor: plugins: Handle packer in seperate files | Handle packer cloning
second commit of refactor
handle require errors
handle cloning og packer
---
[1/4] Refactor: plugins: Add seperate config for each plugins
first commit of Refactor
handle require errors
move config from other places to proper files
---
Move options from init.lua => options.lua
use a local g = vim.g
---
Disable …

Major perf improvements | Handle errors | Better configs | Misc 

---

init.lua
install.sh
lua/mappings.lua
lua/options.lua
lua/pluginList.lua

mappings.lua: Code style fixes | Cleanup options.lua
plugins.bufferline should be as config of nvim-bufferline
install.sh: Use chsh instead of grep /etc/shells

install.sh: Use chsh instead of grep /etc/shells | init: Move bufferline config to pluginList | Misc improvements

---

lua/mappings.lua
lua/pluginList.lua

Closes https://github.com/siduck76/NvChad/issues/164
Added [vim-fugitive](https://github.com/tpope/vim-fugitive) plugin with some main mappings I find useful regarding this plugin.
`:diffget //2` and `:diffget //3` are useful for 3-way merge as the take code from either our or their side.

Add git integration

---

install.sh

- Use more appropriate `-n` flag
- Reword log message

(maint): update conditional check and log message

---

README.md

I've added the invite link of NvChad discord and Changed the badge alt name to discord

Added invite link

---

init.lua
lua/highlights.lua
lua/mappings.lua
lua/options.lua
lua/plugins/lspconfig.lua
lua/plugins/nvimtree.lua
lua/plugins/telescope.lua
lua/telescope/_extensions/themes.lua
lua/theme.lua
lua/utils.lua

firstly....a whole lot of work within this PR was done by @Akianonymus, so a huge thanks to them!
Have to stress that this was a joint PR! :heart:
This PR introduces a Telescope theme switcher, which is compatible with NvChad. 
Critically this means that it supports all of the colours that NvChad supports (for proper plugin colour configuration).
Running the colorscheme changer in NVim: `<LEADER> + t + h`
This *is a WIP*, so if it is merged there will likely need to be another PR to finish this off the functionality that is planned.
- A confirm prompt to set this as the default colourscheme (keep it after NVim restart)
- Proper integration with the planned custom config part of NcChad (for the previous dot point)
- Modification of the UI & various Telescope polishes
Thanks, G-Rowell & …

Chad theme switcher

---

lua/telescope/_extensions/themes.lua
lua/theme.lua

Improvements in startup time
Before:
```
require("theme"): 5.38458ms (24.332083 -> 29.716666)
require("user_config"): 0.030104ms (24.402135 -> 24.432239)
require("base16"): 2.62813ms (24.442708 -> 27.070833)
require("nvim"): 0.317813ms (26.695260 -> 27.013073)
require("highlights"): 0.663593ms (29.051198 -> 29.714791)
require("themes/onedark"): 0.056563ms (29.265364 -> 29.321927)
```
After:
```
require("theme"): 3.69021ms (23.268958 -> 26.959167)
require("user_config"): 0.026771ms (23.325677 -> 23.352448)
require("base16"): 1.0087ms (23.362031 -> 24.370729)
require("nvim"): 0.305208ms (24.063646 -> 24.368854)
require("themes/onedark-base16"): 0.058646ms (24.371979 -> 24.430625)
require("highlights"): 0.627188ms (26.330312 -> 26.957500)
require("themes/onedark"): 0.057448ms (26.521250 -> …
```

base16: Change syntax for new changes in base16 repo

---

lua/mappings.lua
lua/plugins/luasnip.lua

NvChad use luasnip complete but call `vsnip#jumpable` for jump

fix luasnip complete and move it to reasonable place

---

lua/chadrc.lua
lua/mappings.lua

add some useful keymap in insert/command mode with switch to toggle

---

lua/telescope/_extensions/themes.lua
lua/utils.lua

* rearrange functions in utils.lua alphabetically

Fix theme switcher reload | Move reload_theme to utils

---

lua/plugins/statusline.lua

Enables chads to modify statusline filename icons.

(feat) add filename edit/lock icons provider

---

lua/chadrc.lua
lua/mappings.lua
lua/themes/chadracula.lua
lua/themes/everforest.lua
lua/themes/gruvchad.lua
lua/themes/mountain.lua
lua/themes/norchad.lua
lua/themes/one-light.lua
lua/themes/onedark.lua
lua/themes/tokyonight.lua
lua/themes/tomorrow-night.lua

chadrc: looks cleaner this way
move close buffer to misc as it is not dependent on buffer plugin

tree-wide: Format files | Reformat chadrc | Misc

---

lua/chadrc.lua
lua/default_config.lua
lua/pluginList.lua

Hi all,
As we are getting a lot of new users, I think we should enable the cheatsheet by default.
I personally use it all the time myself, and I think it's a must have IMO
G

make cheatsheet enabled by default

---

init.lua
lua/chadrc.lua
lua/default_config.lua
lua/mappings.lua
lua/options.lua
lua/pluginList.lua
lua/plugins/bufferline.lua
lua/plugins/chadsheet.lua
lua/plugins/telescope.lua
lua/telescope/_extensions/terms.lua
lua/theme.lua
lua/utils.lua

---
NvChadUpdater: Make update repo and url configurable | Improvr logging
---
Add NvChadUpdate command and shortcut for it
map leader+uu to it
summary of what it does:
first ask the user for confirmation and tell that the updater is gonna run git reset --hard in config repo and chadrc will be restored
take backup of chadrc in a lua string and locally in a file with chadrc.bak.(random numbers)
git reset on config dir and git pull
whether success or error, restore the chadrc file
if restore fails, then print backup file path
for more deep understanding, read the comments in utils.lua
---
feat: Do not depend on user config | Fix merging of configs
because it is a user config, so our config shoudn't break even we if dont have it
use our own table merge function
move loading config to a …

NvChad Updater | Chadrc Fixes | Cleanup and Formatting | Misc

---

init.lua
lua/chadrc.lua
lua/default_config.lua
lua/mappings.lua
lua/options.lua
lua/pluginList.lua
lua/plugins/bufferline.lua
lua/plugins/chadsheet.lua
lua/telescope/_extensions/terms.lua
lua/theme.lua
lua/utils.lua

---
NvChadUpdater: Make update repo and url configurable | Improvr logging
---
Add NvChadUpdate command and shortcut for it
map leader+uu to it
summary of what it does:
first ask the user for confirmation and tell that the updater is gonna run git reset --hard in config repo and chadrc will be restored
take backup of chadrc in a lua string and locally in a file with chadrc.bak.(random numbers)
git reset on config dir and git pull
whether success or error, restore the chadrc file
if restore fails, then print backup file path
for more deep understanding, read the comments in utils.lua
---
feat: Do not depend on user config | Fix merging of configs
because it is a user config, so our config shoudn't break even we if dont have it
use our own table merge function
move loading config to a …

 NvChad Updater | Chadrc Fixes | Cleanup and Formatting | Misc

---

lua/plugins/configs/lspconfig.lua

Add LSP code action mappings

---

lua/plugins/configs/statusline.lua

Hi all,
this PR handles all Vim modes,
fixing bug in #351 
We previously weren't handling all Vim modes, causing an error in that case.
G

BUGFIX: fix statusline bug, handle all Vim modes

---

lua/colors/themes/aquarium.lua

Made an Aquarium theme for NvChad, hope you guys like it!

Aquarium Theme

---

lua/colors/themes/blossom.lua

adding rayes0's(githubname) blossom theme

added bunny's blossom theme

---

README.md

- Add links in Features section
- Refactor Bloat section
- Refactor Support section
- Add collapsible Themes section

refactor(readme): make readme better

---

lua/plugins/configs/statusline.lua

now it handles dirs too
https://github.com/famiu/feline.nvim/commit/092442db0c7eb6087f0ae2cbeb776781bcc16176

statusline: feline: Use default git provider

---

README.md

This section had some typos and grammatical errors.

Fix grammer in bloat section of README

---

CONTRIBUTING.md

#310 
basically just copied the contributing section from the website and added a permanent link to the discord at the end

chore: add contributing.md

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/plugin.md

Add pr templates like we talked about

chore: Dev pr template

---

lua/plugins/init.lua

this fixes the following issue https://github.com/nvim-telescope/telescope.nvim/issues/1276 and https://github.com/NvChad/NvChad/issues/504

fix: Fixes telescope issue where requiring telescope module #504

---

lua/core/mappings.lua

fix: #501 | delay when use d in visual mode

---

.github/README.md
.github/workflows/format.yml
init.lua
lua/colors/highlights.lua

@siduck76 I am currently testing this by adding some whitespaces to 2 files:
init.lua
lua/colors/highlights.lua
These are for testing purposes so please DON'T EDIT IT.

fix(CI): Fix stylua CI formatter | add charity link

---

.github/README.md

Fixing the README to correct the repo name and get the badges and Chadtributors working again.

Fix: Corrected broken links on badges and contributors so they don't display null info

---

init.lua
lua/colors/init.lua
lua/core/hooks.lua
lua/core/options.lua
lua/core/utils.lua
lua/plugins/configs/nvimtree.lua
lua/plugins/configs/others.lua

* fix some lint warnings
* remove some unneeded code

Cleanup | Format files

---

lua/plugins/configs/statusline.lua

fix feline with new diagnostic api

---

lua/core/default_config.lua
lua/plugins/init.lua

a packerCompile is needed after changin the config value in chadrc

nvimtree: Allow changing lazy load from chadrc | fix #621

---

.github/README.md

Change some old links that were linking to the old repo.

docs: fix some old links

---

.gitignore

vim spell checking puts custom dictionary additions in this directory

chore: add spell directory to gitignore

---

lua/core/mappings.lua

Hey there,
first day chad user here, this is just a small improvement, hopefully I'll be able to figure out a more elegant way to allow users to tweak their mappings soon.
Really enjoying the layout, its got its problems but its brilliant IMO.. thanks
Dunno how you feel on the subject but I'd suggest adding this to the main `find_files` also
Ref: https://github.com/nvim-telescope/telescope.nvim/blob/f06dd06bb1143caa779e492ca37e5f985f0c6157/doc/telescope.txt#L768

when finding all files via Telescope follow symlinks

---

lua/plugins/configs/others.lua

https://github.com/windwp/nvim-autopairs#fastwrap

Enable FastWrap capabilities: 

---

lua/plugins/configs/statusline.lua

Fixes error diagnostics in status line.

fix typo in variable

---

lua/core/default_config.lua
lua/core/utils.lua
lua/plugins/init.lua

Packer override

---

lua/core/utils.lua

Temp fix until init is refactored.

temp fix for removals

---

lua/core/default_config.lua
lua/core/options.lua

Also changed defer to schedule. Same effect but clearer what happens I guess.

restore shada location before load

---

lua/plugins/configs/alpha.lua

Make the alpha config *override* by the users
Headers,
The ascii,
Buttons,
and sections 👀

Make the alpha override-abble

---

lua/colors/highlights.lua
lua/colors/init.lua

Load `hl_override` after the theme loaded

fix: let `hl_override` be compatible with custom themes

---

lua/core/default_config.lua
lua/core/utils.lua
lua/plugins/init.lua

I was wrong it was 11 lines not 3. Sorry.

add back ability to remove plugins

---

lua/core/autocmds.lua

refactor: rewrite auto-commands in lua

---

lua/core/utils.lua
lua/plugins/configs/bufferline.lua
lua/plugins/configs/cmp.lua
lua/plugins/configs/icons.lua
lua/plugins/configs/statusline.lua

Format files
utils.lua: Improve plugin_list function
plugins/cmp: Use keymaps for command line too.

Misc stuff

---

lua/core/mappings.lua

add mapping for :Telescope keymaps

---

lua/core/mappings.lua
lua/plugins/configs/statusline.lua

mapping: Fix p not copy selected text when clipboard in not set

---

examples/init.lua
init.lua
lua/core/mappings.lua
lua/core/options.lua
lua/core/utils.lua
lua/plugins/configs/alpha.lua
lua/plugins/configs/bufferline.lua
lua/plugins/configs/cmp.lua
lua/plugins/configs/icons.lua
lua/plugins/configs/lsp_installer.lua
lua/plugins/configs/lspconfig.lua
lua/plugins/configs/nvimtree.lua
lua/plugins/configs/nvterm.lua
lua/plugins/configs/others.lua
lua/plugins/configs/statusline.lua
lua/plugins/configs/telescope.lua
lua/plugins/configs/treesitter.lua
lua/plugins/init.lua
lua/plugins/packerInit.lua

closes #1053
I will do the same thing to the extensions and the base46 plugins

refactor: add utils to the global scope

---

lua/core/utils.lua

@siduck The title says it all. This implements what I outlined here https://github.com/NvChad/NvChad/issues/1071#issuecomment-1125925059.

fix: default mappings can now be properly disabled, independent of load order

---

lua/core/utils.lua

@siduck disabled key maps would still be displayed in the which-key popup as you can see here:
this is now fixed and disabled key maps are completely removed:

fix: disabled key maps are now completely removed from which-key

---

lua/core/utils.lua

Fixes this https://github.com/NvChad/NvChad/pull/1085#issuecomment-1126941706

fix: handle bug when which-key is not installed

---

lua/core/mappings.lua
lua/core/utils.lua
lua/plugins/configs/lspconfig.lua
lua/plugins/configs/whichkey.lua
lua/plugins/init.lua

@siduck As the title says, this fixes the problems with the `no_whichKey_map` function and also merges all changes from the test branch. I think this also now completes the lspconfig changes so that we can proceed to merge the dev branch into main.

fix: this fixes the `no_whichKey_map` function to now properly work with lspconfig mappings

---

lua/plugins/configs/others.lua

- numToStr/Comment.nvim
- lewis6991/gitsigns.nvim

Make Comment.nvim and gitsigns configs overridable

---

lua/core/lazy_load.lua

fix typo in treesitter init cmds

---

lua/core/default_config.lua
lua/plugins/configs/others.lua

Add a global variable for custom configs to allow for custom luasnip snippets. The directories specified will have to be structured like eg. <https://github.com/rafamadriz/friendly-snippets> (include a similar `package.json`)

feat(luasnip): added luasnippets_path variable for luasnip

---

lua/plugins/configs/lspconfig.lua

Avoid deprecated message always shown on neovim nightly

enhancement: update lsp syntax to support both stable and nightly

---

lua/core/lazy_load.lua
lua/plugins/init.lua

fix(lsp): lsp on_attach was not called at normal mode

---

lua/core/mappings.lua
lua/core/utils.lua
lua/plugins/configs/lspconfig.lua
lua/plugins/configs/whichkey.lua
lua/plugins/init.lua

Use setup of packer to load the mappings before
Load cmp on cmp module

Register mappings only if pluigin is enabled | Misc

---

lua/core/lazy_load.lua

This fixes NvChad not capable of detecting files from git repo as false if such file's $PWD does not have a `.git` directory
@Akianonymus can you have a look? Tyvm

fix: directories not detected as git repos

---

lua/core/init.lua
lua/core/options.lua
lua/plugins/configs/alpha.lua

https://github.com/NvChad/ui/pull/16 pr should be merged before this pr

Cleanup | Misc

---

lua/core/mappings.lua

Fix #1546    
@Akianonymus please have a look, tyvm

fix pasting in select mode

---

lua/core/utils.lua

Both the arguments should be strings.

Fixed notify_once() call

---

lua/plugins/configs/others.lua

…ds case insensitive
just as neovim works

Fix colorizer

---

lua/plugins/init.lua

There is no reason to lazy load this plugin as there is no lua file 
Move it to start to simply loading sequence

Move friendly-snippets to start

---

lua/plugins/configs/nvimtree.lua
lua/plugins/configs/others.lua
lua/plugins/init.lua

This pull request is for branch `v2.0`.
Its contents is same as the ones I submitted against  `main` branch in #1745.
It fix wrong reporitory names into correct ones.
The reason I created this pull request is because I received this comment.
https://github.com/NvChad/NvChad/pull/1744#issuecomment-1384488720

【fix】correct kyazdani42 repos into nvim-tree repos in v2.0 branch

---

lua/core/init.lua

normalize all paths

---

.github/README.md

Before: Many beautiful themes, theme toggler by [our base46 plugin](https://github.com/NvChad/base46)
After: Many beautiful themes, theme toggler by our [base46 plugin](https://github.com/NvChad/base46)

fix: text in readme.md
